dist: bionic

addons:
  postgresql: '10'
  apt:
    update: true  
    packages:
    - jq

before_install:
  - npm install -g csvtojson
  - npm install -g mustache

script:
  - echo '{"hello":"test","world":"test too"}' | jq .
  - echo '{"anarr":[{"hello":"test"},{"world":"test too"}]}' | jq .
  - jq . hello.json
  - jq . hello.json world.json
  - jq . -s hello.json world.json
